### ISSUE TITLE
push to npm?

### ISSUE THREAD

**Issue by ianjuma** [habbes/ussd-menu-builder#1]
@habbes maybe push this package to npm and also a PR on the at-node.js README on how to use this?

**Comment by habbes** [comment]
Okay, I will try to do so by the end of the week. I will add tests and a more comprehensive guide.

**Comment by habbes** [comment]
@ianjuam I've written unit tests, next is to work on a proper documentation

**Comment by ianjuma** [comment]
@habbes awesome! I'm already using this; playing around with the next USSD app/ demo. Haven't made much progress

**Comment by habbes** [comment]
@ianjuma oh great. Though may have made some changes to make sure all tests pass. I'll keep you posted. Hopefully the doc will be done soon.

**Comment by habbes** [comment]
And @ianjuma, are you hiring devs at Africastalking, I'd like to join you guys.

**Comment by ianjuma** [comment]
@habbes of course! We are always looking for good talent. I'll do a couple of introductions; always happy to :smile:

**Comment by habbes** [comment]
@ianjuma Oh cool. Let me know how it goes, I have already published the module on NPM, now just updating the documentation.

**Comment by habbes** [comment]
@ianjuma I've updated the docs with a more comprehensive guide. Hopefully now it makes sense.

**Comment by habbes** [comment]
@ianjuma my contacts: hello@habbes.xyz or student: 13s01acs014@anu.ac.ke

**Comment by ianjuma** [comment]
already did the intro :smile:
