### ISSUE TITLE
How can I handle return to the previous menu?

### ISSUE THREAD

**Issue by eshe-huli** [habbes/ussd-menu-builder#17]
Please I'm doing an app in ussd with your menu builder and I want to know how I can implement a return to previous by taping "0" on every screen to go to the previous one and also when there been also able to work around

**Comment by habbes** [comment]
Hello @eshe-huli,

I did not understand what the last part of your question means "and also when there been also able to work around".

If the previous menu is statically determined, i.e. from a given menu there's only one "previous" menu that you can go to, then you can easily define that in the `next` object of the menu, e.g.

```js
menu.startState({
  run: () => {
      menu.con('Page 1');
   },
  next: {
    1: 'page2.1',
    2: 'page2.2'
  }
})
.state('page2', {
  run: () => {
     menu.con('Page 2\n1. Option 1\n2. Option 2\0. Go back');
  },
  next: {
    0: '__start__', // links back to home page,
    1: 'page3'
 }
})
.state('page3', {
  run: () => {
    menu.con('...');
  },
  next: {
    0: 'page2', // links back to page2
  }
});
```

If, on the other hand, the "previous" state should be determined dynamically, then in that case you might have to keep track of the visited states in the session or something along those lines. Let me know if this is what you meant to ask. And also, share a more concrete example of your use-case and desired outcome.

**Comment by eshe-huli** [comment]
thank I where using "go" instead of just taping the name in next,
I also found out that the "__start__" might be write all in lower case

**Comment by habbes** [comment]
Hello @eshe-huli. I don't know what you meant by "the **start** might be write all in lower case". But generally it sounds from your message that you found a solution to your issue. So I will go ahead and close this issue. Feel free to open another issue if you face other problems.
