### ISSUE TITLE
Session Management

### ISSUE THREAD

**Issue by andela-ooladayo** [habbes/ussd-menu-builder#2]
Presently the module is using system memory to keep track of each section, which might not scale well when ran on clusters or if the process restarts. Please, can we have an option to add centralized in-memory storage like Redis?

**Comment by habbes** [comment]
@andela-ooladayo Do you mean for storing sessions?

**Comment by habbes** [comment]
@andela-ooladayo the library right now does not deal with Session storage directly. It only stores the sessionId as retrieved from Africastalking, so you'd you have to right your own session logic to fetch and store the appropriate data based on the sessionId. I had initially included a session object connected to Redis but, that was project specific, in the spirit of decoupling concerns and keeping the library general and backe-end agnostic I removed it. So for now you'd have to bring your own session-management logic.

**Comment by habbes** [comment]
@andela-ooladayo but I can work on adding a feature for to make it easier to work with sessions while still keeping it backend-agnostic.

**Comment by ianjuma** [comment]
I'd prefer that too, managing state/ sessions at that point should no be the state machines logic; also that could be easily extended.

**Comment by andela-ooladayo** [comment]
@habbes That will be nice.

**Comment by habbes** [comment]
Ok I'll work on it. I'll post the idea I have for implementing it here first for review.

**Comment by habbes** [comment]
@andela-ooladayo @ianjuma So basically this is the approach I have in mind, add method to configure a custom session manager of your choice by supplying your own implementation of your ```get```, ```set``` and ```delete``` methods and then the UssdMenu would use that on an underlying session object

```javascript

// configure custom session handler
menu.sessionConfig({
    get: function(sessionId, key, callback){
        // your implementation for getting a value from the session by key
    },
    set: function(sessionId, key, value, callback){
       // your implementation for storing a key-value in the session
    },
    deleteSession: function(sessionId, callback){
       // your implementation for removing the session (called when USSD session ends)
    }

});

```

And once configured, session object can be used within states:

```javascript

menu.state('statename', {
   run: () => {
      menu.session.get('firstName').then(name => {
          ...
      });
   },
   ...
});

```
So this approach still decouples the menu from the session management and makes it backend-agnostic allowing you to create your own custom implementation that fits your own backend, whether you store your session data in redis, memcached, database, filesytem or memory, is up to you.

For convenience I'll create a separate pluggable package that contains implementations of these methods for redis and for memory (using ordinary dicts) then other devs can create any other connector they need.

```javascript
const UssdMenu = require('ussd-menu-builder');
const sessionManager = require('ussd-menu-session');

menu = new UssdMenu();
menu.sessionConfig(sessionManager.get('redis'));
...
```

Let me know what you think of this approach.

**Comment by andela-ooladayo** [comment]
I like your approach!

**Comment by andela-ooladayo** [comment]
I like your approach!

**Comment by habbes** [comment]
@andela-ooladayo @ianjuma I've added support to define your own session handlers in this PR #3, I'll update the docs then merge and push to npm.

**Comment by habbes** [comment]
@andela-ooladayo @ianjuma update the docs, I guess it's okay to merge now

**Comment by andela-ooladayo** [comment]
Thank you @habbes. Excellent work.
