### ISSUE TITLE
Press Zero to Go Back

### ISSUE THREAD

**Issue by Bascil** [habbes/ussd-menu-builder#22]
Kindly explain how you would implement the ability to demote a session level like press zero to go back

**Comment by habbes** [comment]
Hi @Bascil, I think the easiest way would be to add `'0'` to the `next` object of each state and then just map it to the state that's supposed to be the previous state.

In the example below `state1` comes before `state2` and `state3`. So pressing zero in states `state2` and `state3` should take you back to `state1`. So I add a transition from `state2` to `state1` on the `0` input, and same thing from `state3` to `state1`.

The menu builder itself doesn't know anything about the order of states, that's application and use-case specific.

```js
menu.state('state1', {
    run: () => {
    },
    next: {
      '1': 'state2',
      '2': 'state3',
      '0': 'state0'
    }
    
});

menu.state('state2', {
    run: () => {
        // ...
    },
    next: {
        '1': 'state4',
        '2': 'state5',
        '0': 'state1'
    }
});

menu.state('state3', {
    run: () => {
        // ...
    },
    next: {
        '1': 'state6',
        '2': 'state7',
        '0': 'state1'
    }
});
```

**Comment by Bascil** [comment]
Thanks, got it working
