### ISSUE TITLE
Unable to share data between states

### ISSUE THREAD

**Issue by Bascil** [habbes/ussd-menu-builder#26]
Is there a way to pass data as arguments to the next state?

**Comment by BayoKwendo** [comment]
I have come to conclusion that Redis can do this job perfectly.

**Comment by harmonizerblinks** [comment]
> you can use sessions set and get to pass data between states

you can use sessions set and get to pass data between states

**Comment by habbes** [comment]
Use sessions to share data between state. See: https://github.com/habbes/ussd-menu-builder?tab=readme-ov-file#sessions
You can implement session logic using redis, database, in-memory dictionary (for single-process servers) or whatever works for your use case
