### ISSUE TITLE
Prepend a message after data invalidations

### ISSUE THREAD

**Issue by ErickMwazonga** [habbes/ussd-menu-builder#27]
When the user is taken back to the same step due to data invalidations. It should add an invalid message.

**Comment by njau58** [comment]
@ErickMwazonga Did you ever find a solution to this?

**Comment by ErickMwazonga** [comment]
@njau58, unfortunately, I did not.

**Comment by habbes** [comment]
You can use the `defaultNext` state to handle the case where the user enters invalid data. Then in that state you can display the invalid message. See: https://github.com/habbes/ussd-menu-builder?tab=readme-ov-file#defining-states
