### ISSUE TITLE
Paginate List of Records

### ISSUE THREAD

**Issue by macleash90** [habbes/ussd-menu-builder#38]
Is there a way the library can handle the pagination of a list of records

**Comment by habbes** [comment]
@macleash90 the library does not handle pagination by default. You can use one state to display the records and then use the session to keep track of which page you're displaying. So you can fetch and display the paginated data based on the session and the "next page" state should return back to the same state but with updated session data.

**Comment by macleash90** [comment]
Thank you @habbes 
I don't really get what you are saying and how to implement it please, I would be very grateful if you could provide some code to demonstrate what you are saying. So that myself and others can use that please.
