### ISSUE TITLE
States aren't respected when declared in state.next

### ISSUE THREAD

**Issue by aframe82** [habbes/ussd-menu-builder#6]
I have a set of three options set up in menu.startState, that are all respected just fine.

However, when I set up further states with a regex, or otherwise, those rules aren't respected. The only rules that are used are the initial rules declared in startState:

```
menu.startState({
	run: function() {
		menu.con('Please Choose:' + 
			'\n1. Sign Up' + 
			'\n2. View Orders' + 
			'\n3. View Produce'
		);
	},
	next: {
		'1': 'register.start',
		'2': 'viewOrders',
		'3': 'viewProduce'
	}
});

// this function is encountered, but it never accepts the next route 
menu.state('register.start', {
	run: function() {
		menu.con('Enter your name');
	},
	next: {
		'*^[a-zA-Z\\s]*$': 'register.address'
	}
});

// this is never encountered
menu.state('register.address', {
	run: function() {
		console.log(menu.val);
		menu.con('Please enter your address:')
	},
	next: {
		'*^[a-zA-Z0-9\\s\\,]*$': 'register.produce'
	}
});
```

Admittedly I'm using a simulator [(this one)](http://www.ideamart.lk/idea-pro/start-up-the-simulator) but I'm not confident this is where the issue lies.

**Comment by habbes** [comment]
Hello @aframe82, thanks for your comment. Admittedly I have not used that particular simulator and I'm not sure the kind of data it's sending. Could you share the raw data of the request sent by your simulator, and also the USSD gateway you're using? This library was written to be compatible with [Africastalking USSD API](http://docs.africastalking.com/ussd).

**Comment by habbes** [comment]
@aframe82, I've done a quick skim through the [Ideamart USSD API](http://www.ideamart.lk/idea-pro/ussd), which I assume is what you're using. Though different from the one the library was intended for, the `message` parameter sent in the request seems to be similar in format to the `text` parameter sent by Africastalking.  However I have spotted a few differences:  Africastalking does not include the service code as part of the `text` parameter. Furthermore, Africastalking concatenates the user responses of previous hops in each new hop, separated by the `*` character, and the library relies heavily on the assumption that that's how the input is formatted. Does Ideamart do this as well? Please share the paramerters you're providing the constructor to make it easier to find the issue.

**Comment by aframe82** [comment]
To be honest, I'm just using the simulator as a way to interact with the API.

In fact, the project that I'm working on has a need to use USSD in multiple countries from multiple providers (Africastalking don't support most of the countries we'll be live in), so I'm testing this lib to see how feasible that is, as I like the usability of it.

But, as you asked, the request is below:

```
POST / HTTP/1.1
Content-Type: application/json
Accept: application/json
User-Agent: Apache CXF 2.6.1
Cache-Control: no-cache
Pragma: no-cache
Host: d687ffde.ngrok.io
Content-Length: 222
X-Forwarded-For: 128.90.105.29

{"ussdOperation":"mo-cont","sourceAddress":"tel:94771122336","requestId":1482258491552,"vlrAddress":"some vlr address","sessionId":"123","applicationId":"APP_000001","message":"Customer Name","encoding":"440","version":"1.0"}
```

The sim sends `mo-init` on the first request, and then `mo-cont` on further requests.

**Comment by aframe82** [comment]
OK, I've dug a little further into the docs and code.

I was unaware that previous answers were prepended to each new answer with an asterisk delimiter.  When I mimic that in the simulator - it works just as expected.

`1*Customer Name*4` works fine.

Is this a feature of USSD in general, or is it a feature of the AfricasTalking API?

I would have thought it would make more sense to hold the state in some sort of data store and perform a lookup of sessionId and phoneNumber to determine the correct route.

Or am I on the wrong train of thought there?

**Comment by habbes** [comment]
@aframe82 yeah, that's how the AfricasTalking API works, I am not certain whether it is a feature of USSD in general, but it seems not since the Ideamart API you're using seem to have a different standard altogether. If Ideamart does not prepend previous answers to the each request then the library would need some major patching to support this use case. Maybe it could be a worthy endeavour to support that. But it would be good to know of other USSD APIs and how they work in order to have a more generic library.

**Comment by habbes** [comment]
@aframe82 one workaround, more of hack really, if you would still want to make use of the library as it is, is to manually store answers of the current session based on the `sessionId`, then on each request you load these answers from the data store, join them in one string delimited by the `*` character then pass that to the arguments of the `menu.run` method.

**Comment by aframe82** [comment]
> manually store answers of the current session based on the `sessionId`

@habbes This is what I've done.

So that I can still make use of the library, I've linked it to MongoDB to save the sessions, then for each new message that is received with the same `phoneNumber` and/or `sessionId` I'm just appending the last `text` received to what I've been sent this time and then running the `menu`.

Works pretty well.

I'll add the code before I close the issue.

**Comment by habbes** [comment]
Counting this as solved.
