### ISSUE TITLE
Can't set headers after they are sent.

### ISSUE THREAD

**Issue by musale** [habbes/ussd-menu-builder#7]
I use your lib in production and I noticed that when there's many USSD requests, they will end up without being resolved throwing this error

```
app[web.1]: Error: Can't set headers after they are sent.
app[web.1]:     at validateHeader (_http_outgoing.js:491:11)
app[web.1]:     at ServerResponse.setHeader (_http_outgoing.js:498:3)
app[web.1]:     at ServerResponse.header (/app/node_modules/express/lib/response.js:767:10)
app[web.1]:     at ServerResponse.send (/app/node_modules/express/lib/response.js:170:12)
app[web.1]:     at UssdMenu.menu.run.ussdResult [as onResult] (/app/src/ussd/index.ts:33:11)
app[web.1]:     at UssdMenu.callOnResult (/app/node_modules/ussd-menu-builder/lib/ussd-menu.js:20:18)
app[web.1]:     at UssdMenu.con (/app/node_modules/ussd-menu-builder/lib/ussd-menu.js:26:14)
app[web.1]:     at menuOps (/app/src/ussd/registration.ts:222:17)
app[web.1]:     at <anonymous>
app[web.1]: (node:27) UnhandledPromiseRejectionWarning: Error: Can't set headers after they are sent.
app[web.1]:     at validateHeader (_http_outgoing.js:491:11)
app[web.1]:     at ServerResponse.setHeader (_http_outgoing.js:498:3)
app[web.1]:     at ServerResponse.header (/app/node_modules/express/lib/response.js:767:10)
app[web.1]:     at ServerResponse.send (/app/node_modules/express/lib/response.js:170:12)
app[web.1]:     at UssdMenu.menu.run.ussdResult [as onResult] (/app/src/ussd/index.ts:33:11)
app[web.1]:     at UssdMenu.callOnResult (/app/node_modules/ussd-menu-builder/lib/ussd-menu.js:20:18)
app[web.1]:     at UssdMenu.end (/app/node_modules/ussd-menu-builder/lib/ussd-menu.js:31:14)
app[web.1]:     at endMenu (/app/src/ussd/registration.ts:232:8)
app[web.1]:     at menuOps (/app/src/ussd/registration.ts:226:5)
app[web.1]:     at <anonymous>
```
It's the same request resolved twice or more. I'm working on a fix but I have so far hit a dead end.

**Comment by habbes** [comment]
@musale thanks for opening this and sorry for the late reply, I've just seen this.
Could you show the snippet of code you're using to register the ussd handler?

**Comment by habbes** [comment]
@musale I think I have an idea of what could be causing that error:

The library is most likely used by creating one instance of the `UssdMenu` and using this single instance to define states. And each ussd request triggers a call to the `menu.run(args, resultHandler)` method.

However there's a flaw in the design: while the `menu.run()` is called separately for each request and possibly with a different result handler each time, the result handler is actually attached to the menu instance as `menu.onResult` object. So A new request will replace this function with the new handler. So if one request takes time to complete, its handler might be replaced by that of a more recent request, so when it'll trigger the wrong handler when it's complete. And if it triggers a handler that has already been called, it will cause `res.send` to be called twice, which would cause the error you're referring to.

**Comment by habbes** [comment]
@musale I have an idea for a fix. Instead of using `menu.con`, and `menu.end` and an `onResult` object that's attached to the instance, I'll add `con` and `end` functions to the args passed to the `state.run` function and ensure that they call the correct handler.

I will also deprecate `menu.con`, `menu.end` and `menu.onResult`, I could keep them for backwards compatibility but add a warning against their usage.

I will try to work on an update this coming week.

**Comment by habbes** [comment]
@musale until I have an update ready, I could propose the following temporary fix:

Create a new menu instance for each request, that way you avoid the issue of the handler that gets replaced.

Instead of:

```javascript
const menu = new UssdMenu();
// your states
menu.startState(...);
menu.state(...);

// register handler
app.post('/ussd', (req, res) => {
    menu.run(req.body, msg => res.send(msg);
}
```
Try this: 

```javascript
function createMenu () {
  const menu = new UssdMenu();
  // your states
  menu.startState(...);
  menu.state(...);
  
  return menu;
}

// register handler
app.post('/ussd', (req, res) => {
    // creates new instance each time
    const menu = createMenu();
    menu.run(req.body, msg => res.send(msg);
}
```

**Comment by habbes** [comment]
@musale if you have a better suggestion for a fix, let me know. Also, if you see a potential problem or flaw with my proposed update, let me know as well.

Thanks for pointing this out.

**Comment by musale** [comment]
@habbes thank you for the follow-up. I haven't had time to try out the suggestions as I've been very ill. I was declaring a global `menu` instance and as you've explained, that was the cause of the requests being terminated. I will try creating the menu for each instance and then give you the feedback for it. However, this might not be soon. I was looking for a fix but like I mentioned, I got sidetracked. I will update you if anything works(or not hehe) thank you!

**Comment by habbes** [comment]
@musale I've been away for a while and have been bogged down by work. I will try to get back to this issue this coming week or the next.

**Comment by Marcosmaliki** [comment]
> @musale until I have an update ready, I could propose the following temporary fix:
> 
> Create a new menu instance for each request, that way you avoid the issue of the handler that gets replaced.
> 
> Instead of:
> 
> ```js
> const menu = new UssdMenu();
> // your states
> menu.startState(...);
> menu.state(...);
> 
> // register handler
> app.post('/ussd', (req, res) => {
>     menu.run(req.body, msg => res.send(msg);
> }
> ```
> 
> Try this:
> 
> ```js
> function createMenu () {
>   const menu = new UssdMenu();
>   // your states
>   menu.startState(...);
>   menu.state(...);
>   
>   return menu;
> }
> 
> // register handler
> app.post('/ussd', (req, res) => {
>     // creates new instance each time
>     const menu = createMenu();
>     menu.run(req.body, msg => res.send(msg);
> }
> ```

This solution doesn't work. I'm curious if anyone has a fix for this; if not, I can join in on the fun to find a fix.

**Comment by musale** [comment]
@Marcosmaliki you can have a go at it. I no longer work on the project that required this dependency, I doubt I will pursue it any further 😺
